### ISSUE TITLE
Fix CORS bugs

### ISSUE THREAD

**Issue by abungay** [talos-org/server#25]
Fix CORS (CROSS ORIGIN RESOURCE SHARING) bugs, its very annoying requiring a plugin on the browser to be able to make the REST calls to work -> might need to not use the Flask testing server, route through NGINX or GNUICORN?

We have already tried to use Flask modules such as flask-cors to add the Access-Control-Accept-Origin: * headers but no luck, browser REST calls still fail. This may have been caused by using the test web server for Flask.

**Comment by yeskunall** [comment]
Adding the `critical` label because this actually affects our demo. @zaidoon1 can you please look into this?

We can’t expect our users to also install the same extension as we do. So, like I said before, we can use NGINX or Gunicorn for this. I would have preferred [Caddy](https://caddyserver.com/), but Caddy doesn't support the uWSGI protocol as of now, so we should probably go for the next best option which is Gunicorn.

**Comment by abungay** [comment]
Fixed in latest merge into master. Restructuring of Flask app and addition of flask-cors module by @zaidoon1 solved this issue.
